# Generated by Django 4.0.6 on 2022-07-06 15:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=12, verbose_name='品牌名称')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌管理',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='生产商')),
                ('M_license', models.CharField(max_length=100, verbose_name='生产许可证号')),
                ('address', models.CharField(max_length=100, verbose_name='生产商地址')),
            ],
            options={
                'verbose_name': '生产商',
                'verbose_name_plural': '生产商管理',
            },
        ),
        migrations.CreateModel(
            name='Shangping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下架'), (1, '上架'), (2, '放入仓库')], default='0', verbose_name='商品状态')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=30, verbose_name='产品名称')),
                ('dosage', models.IntegerField(choices=[(0, '固体饮料'), (1, '压片糖果'), (2, '代用茶'), (3, '其他')], verbose_name='产品类型')),
                ('standards', models.CharField(max_length=50, verbose_name='产品标准号')),
                ('mixture', models.TextField(verbose_name='配料表')),
                ('cat', models.CharField(max_length=100, verbose_name='商品标签')),
                ('types', models.IntegerField(choices=[(0, '罐装'), (1, '瓶装'), (2, '袋装'), (3, '盒装'), (4, '组合装'), (5, '其他')], default='0', verbose_name='包装种类')),
                ('first', models.CharField(max_length=15, verbose_name='装箱数')),
                ('pack', models.IntegerField(choices=[(0, '袋'), (1, '瓶'), (2, '支'), (3, '其他')], verbose_name='最小包装')),
                ('net_veight', models.CharField(max_length=30, verbose_name='净含量')),
                ('shelf_life', models.CharField(max_length=30, verbose_name='保质期')),
                ('storge', models.CharField(max_length=100, verbose_name='储存方法')),
                ('edible', models.CharField(max_length=200, verbose_name='食用方法')),
                ('pr_name', models.CharField(max_length=100, verbose_name='宝贝标题')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='零售价')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='折扣价')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='产品详情')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand', verbose_name='品牌名')),
                ('manu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.manufacturer', verbose_name='生产商')),
            ],
            options={
                'verbose_name': '产品详情',
                'verbose_name_plural': '产品详情',
                'db_table': 'db_shangpings',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='manu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.manufacturer'),
        ),
    ]
