# Generated by Django 4.0.6 on 2022-07-15 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.IntegerField(choices=[(0, '下架'), (1, '上架'), (2, '放入仓库')], default='0', verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='status',
            field=models.IntegerField(choices=[(0, '下架'), (1, '上架'), (2, '放入仓库')], default='0', verbose_name='商品状态'),
        ),
    ]
