# Generated by Django 4.0.6 on 2022-07-18 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_addtime_brand_is_delete_brand_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sptt_fist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=20, null=True, verbose_name='图片名称')),
                ('uplod_img', models.FileField(blank=True, null=True, upload_to='static/img/商品头图', verbose_name='展示图')),
            ],
        ),
        migrations.AddField(
            model_name='shangping',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/img/商品头图', verbose_name='商品主图'),
            preserve_default=False,
        ),
    ]
