# Generated by Django 4.0.6 on 2022-07-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sptt_fist_shangping_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangping',
            name='pic',
            field=models.ImageField(upload_to='uploads/商品头图', verbose_name='商品主图'),
        ),
    ]
