# Generated by Django 4.0.6 on 2022-07-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_shangping_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sptt_fist',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='addtime',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='addtime',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='status',
        ),
    ]
