# Generated by Django 4.0.6 on 2022-07-21 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_manufacturer_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangping',
            name='suitable_for',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='适宜人群'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shangping',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='食用周期（天）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shangping',
            name='unsuitable_for',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='不适宜人群'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cont',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='联系电话'),
        ),
    ]
