# Generated by Django 4.0.6 on 2022-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_shangping_suitable_for_shangping_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='odm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='委托商'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='odm_cont',
            field=models.IntegerField(blank=True, null=True, verbose_name='联系方式'),
        ),
    ]
