# Generated by Django 4.0.6 on 2022-07-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_manufacturer_odm_manufacturer_odm_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='odm_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='委托商地址'),
        ),
    ]
