# Generated by Django 4.0.6 on 2022-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_manufacturer_odm_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangping',
            name='pic1',
            field=models.ImageField(default='', upload_to='uploads/产品图片/', verbose_name='图片1'),
        ),
        migrations.AddField(
            model_name='shangping',
            name='pic2',
            field=models.ImageField(default='', upload_to='uploads/产品图片/', verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='shangping',
            name='pic3',
            field=models.ImageField(default='', upload_to='uploads/产品图片/', verbose_name='图片3'),
        ),
        migrations.AddField(
            model_name='shangping',
            name='pic4',
            field=models.ImageField(default='', upload_to='uploads/产品图片/', verbose_name='图片4'),
        ),
        migrations.AddField(
            model_name='shangping',
            name='pic5',
            field=models.ImageField(default='', upload_to='uploads/产品图片/', verbose_name='图片5'),
        ),
        migrations.AddField(
            model_name='shangping',
            name='video',
            field=models.FileField(default='', upload_to='uploads/产品视频/', verbose_name='产品视频'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cont',
            field=models.IntegerField(blank=True, null=True, verbose_name='联系电话'),
        ),
    ]
