# Generated by Django 4.0.6 on 2022-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_shangping_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangping',
            name='pic1',
            field=models.ImageField(default='', upload_to='', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='shangping',
            name='pic2',
            field=models.ImageField(default='', upload_to='', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='shangping',
            name='pic3',
            field=models.ImageField(default='', upload_to='', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='shangping',
            name='pic4',
            field=models.ImageField(default='', upload_to='', verbose_name='图片4'),
        ),
        migrations.AlterField(
            model_name='shangping',
            name='pic5',
            field=models.ImageField(default='', upload_to='', verbose_name='图片5'),
        ),
        migrations.AlterField(
            model_name='shangping',
            name='video',
            field=models.FileField(default='', upload_to='', verbose_name='产品视频'),
        ),
    ]
