# Generated by Django 4.0.6 on 2022-07-06 14:33

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='公司介绍')),
                ('linkman', models.CharField(blank=True, max_length=10, null=True, verbose_name='联系人')),
                ('phone', models.IntegerField(verbose_name='联系电话')),
                ('MP', models.IntegerField(verbose_name='联系人手机号')),
            ],
            options={
                'verbose_name': '公司介绍',
                'verbose_name_plural': '公司介绍',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类描述')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='日期')),
                ('tags', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '资讯分类',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='视频')),
                ('topic', models.CharField(max_length=100, verbose_name='标题')),
            ],
            options={
                'verbose_name': '所有视频',
                'verbose_name_plural': '所有视频',
            },
        ),
        migrations.CreateModel(
            name='Xinw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=200, verbose_name='新闻标题')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '所有资讯',
            },
        ),
    ]
