# Generated by Django 4.0.6 on 2022-08-26 06:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='公司介绍'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='caption',
            field=models.CharField(max_length=30, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='xinw',
            name='caption',
            field=models.TextField(max_length=200, verbose_name='资讯标题'),
        ),
        migrations.AlterField(
            model_name='xinw',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='资讯内容'),
        ),
    ]
