# Generated by Django 4.0.6 on 2022-08-26 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
        ('company', '0002_alter_about_text_alter_topic_caption_and_more'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date'], 'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AddField(
            model_name='comment',
            name='xinw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.xinw'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sharer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.sharer'),
        ),
    ]
